### ISSUE TITLE
java.lang.IllegalStateException: Cannot start this animator on a detached view!

### ISSUE THREAD

**Issue by Obirawa** [wooplr/Spotlight#15]
This issue is caused by this line:

Animator anim = ViewAnimationUtils.createCircularReveal(this, this.targetView.getPoint().x, this.targetView.getPoint().y, 0.0F, finalRadius);

inside SpotlightView.startRevealAnimation()

I'm not sure but i believe it could be resolved by not using postDelayed inside the show() function because in some cases the view is destroyed before the handler executes and thus width or height = 0

here is the complete stacktrace:

Fatal Exception: java.lang.IllegalStateException: Cannot start this animator on a detached view!
       at android.view.RenderNode.addAnimator(RenderNode.java:824)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:277)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:261)
       at android.animation.RevealAnimator.(RevealAnimator.java)
       at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:48)
       at com.wooplr.spotlight.SpotlightView.startRevealAnimation(SpotlightView.java:351)
       at com.wooplr.spotlight.SpotlightView.access$100(SpotlightView.java:52)
       at com.wooplr.spotlight.SpotlightView$1.run(SpotlightView.java:312)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5538)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by deplacer** [comment]
I also having this issue.. pointing to>
```
com.wooplr.spotlight.SpotlightView.startRevealAnimation (SpotlightView.java:351)
com.wooplr.spotlight.SpotlightView.access$100 (SpotlightView.java:52)
com.wooplr.spotlight.SpotlightView$1.run (SpotlightView.java:312)
```

**Comment by igorregis** [comment]
I'm receiveing this same crash report on my app. Since it's outside my code, I can't handle it.

It seens that the user closed the activity during the rendering process of the spotlight

`Fatal Exception: java.lang.IllegalStateException: Cannot start this animator on a detached view!
       at android.view.RenderNode.addAnimator(RenderNode.java:812)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:300)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:282)
       at android.animation.RevealAnimator.(RevealAnimator.java)
       at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:55)
       at com.wooplr.spotlight.SpotlightView.startRevealAnimation(SpotlightView.java:351)
       at com.wooplr.spotlight.SpotlightView.access$100(SpotlightView.java:52)
       at com.wooplr.spotlight.SpotlightView$1.run(SpotlightView.java:312)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)`

**Comment by Obirawa** [comment]
@igorregis you can download the library and remove the postdelayed, I tested it and it works

**Comment by igorregis** [comment]
I'm already using 1.2.2 relrease. Is there another file?

**Comment by igorregis** [comment]
Ok, now I realised that I need to remove the postdelayed call, right?

**Comment by deplacer** [comment]
for the meantime I set enableRevealAnimation to false.

**Comment by drjunior** [comment]
I also have the same problem described. There is an updated planed adressing this issue? Thanks for your support.

**Comment by vanipabhu** [comment]
Hi am also facing the same issue while using SpotlightSequence it is crashing if I exit from app before the purpose is finished. Is the issue solved

**Comment by phantuanphong** [comment]
me too

**Comment by Pilou44** [comment]
I also have the problem. Is this API still maintained ? There has been no update for 5 month.

**Comment by gkhncnr** [comment]
Resolved?

**Comment by mayurwish** [comment]
This issue still exist. Reproduced on 

Android version: Android 7.0
Device: Galaxy S8+ (dream2lte)
Manufacturer: Samsung 
RAM (MB) 4096 
Screen size 1080 × 2008 
Screen density (dpi) 420 
Native platform armeabi-v7a 
OpenGL ES version 3.2 
CPU make Samsung 
CPU model Exynos 8895

Kindly find below log 
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.gocheckapp.model.response.chats.ChatMessage.getMessageTime()' on a null object reference
       at com.gocheckapp.adapters.ChatExchangeAdapter.onBindViewHolder(ChatExchangeAdapter.java:204)
       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
       at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:282)
       at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:336)
       at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:349)
       at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:356)
       at android.support.v7.widget.GapWorker.run(GapWorker.java:387)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6322)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by abhay994** [comment]
this worked for me
YOUr_View.post(new Runnable() {
             @Override
             public void run() {
                 animation();
             }
         });
Example
linearLayout.post(new Runnable() {
             @Override
             public void run() {
                 animation();
             }
         });

**Comment by dhavalwooplr** [comment]
Please check #60 for fix.

**Comment by CHRehan** [comment]
Check your Layout is attached to window or not by using r`ootLayout.isAttachedToWindow()` method.

```
 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
        if (rootLayout!= null) {

            if(rootLayout.isAttachedToWindow()) {
                ViewTreeObserver viewTreeObserver = drawerLayout.getViewTreeObserver();
                if (viewTreeObserver.isAlive()) {
                    viewTreeObserver.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
                        @Override
                        public void onGlobalLayout() {
                            startRevealAnimation(rootLayout);
                            rootLayout.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                        }
                    });
                }
            }
        }
```
